### ISSUE TITLE
How do I modify the transparency of the notification menu?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [surajmandalcell/elementary-x#15]
![screenshot from 2019-02-10 18 29 06](https://user-images.githubusercontent.com/12076232/52532651-76d20b80-2d63-11e9-9f3a-4d58db95d210.png)
How to modify the transparency of the notification menu and right-click menu?

**Comment by surajmandalcell** [comment]
Find the class using gtk-inspector and try changing background color values. I'm no longer using elementary os this not working on themes so cant help much, sorry 😞

**Comment by Yakumo-Yukari** [comment]
> Find the class using gtk-inspector and try changing background color values. I'm no longer using elementary os this not working on themes so cant help much, sorry

Thank you for your reply and suggestions.
