### ISSUE TITLE
Tab height incorrect

### ISSUE THREAD

**Issue by selwynorren** [surajmandalcell/elementary-x#31]
Hello,

Seems the tab height is incorrect in Elementary OS 6.1. This is both for light and dark themes

I find this in Terminal, Files and in Code where tabs are present.

I have attached some screenshot of the tab height in code
![tab-heigh-codet](https://user-images.githubusercontent.com/570607/177840785-e67f3015-1e08-4296-88cb-df0c830b7d97.jpg)

Here is a screenshot of the tab height in files
![tab-height-files](https://user-images.githubusercontent.com/570607/177840870-853454f1-8025-45d7-a45c-d10ebad328b2.jpg)

This is the default correct tab height
![tab-height-correct](https://user-images.githubusercontent.com/570607/177840905-08831085-ccbb-4c17-8ca3-4edae75b2c01.jpg)

**Comment by xisa-gh** [comment]
Hi, 
Appending the code to /elementary-x/gtk-3.0/gtk-widgets.css works for me:

tabs {
font-size: 12px;
margin-top: 5px;
}

**Comment by surajmandalcell** [comment]
Unfortunately I moved away from elementary a while ago but @xisa-gh I trust your code works? I'm pushing with your change so hope it works.

**Comment by xisa-gh** [comment]
The code works for elementary-x in Elementary Odin and Horus. Btw, "font-size" is not necessarily needed in this case.

**Comment by surajmandalcell** [comment]
removed font-size
