### ISSUE TITLE
"Fix" for GNOME 3.28 Apps

### ISSUE THREAD

**Issue by ChocolateMilkGod** [surajmandalcell/elementary-x#7]
GNOME 3.28 apps don't have .image-button in the buttons in the headerbar, causing borders.

This seems to "fix" it. by fix it, a work around.

```
.titlebar button:not(.titlebutton):not(.text-button):not(.radio),
.titlebar .button:not(.titlebutton):not(.text-button):not(.radio)
{
    padding: 3px;
    border-radius: 99px;
    border: 1px solid transparent;
    background-image: none;
    box-shadow: none;

}
```

**Comment by surajmandalcell** [comment]
Can you tell me which application are you using? so i can test the same and merge if it works.

**Comment by ChocolateMilkGod** [comment]
Geary, Corebird. Probably best for app specific work-arounds though.

Before
![before](https://user-images.githubusercontent.com/38067056/40722469-54ee4952-6414-11e8-81f6-3dfb2793fe05.png)

After
![after](https://user-images.githubusercontent.com/38067056/40722464-52ed1ee4-6414-11e8-948e-957a807eb195.png)

**Comment by surajmandalcell** [comment]
I'm testing it rn, will check 2,3 apps and if it does not have any issues ill merge it!

**Comment by surajmandalcell** [comment]
So this happens to other elements 
Before :
![before](https://user-images.githubusercontent.com/11650177/40723850-63551592-643d-11e8-883f-cd567897ae2b.png)
After :
![after](https://user-images.githubusercontent.com/11650177/40723870-6e96876a-643d-11e8-8c8e-8d1ab128a40c.png)

**Comment by ChocolateMilkGod** [comment]
I amended the original issue and that shouldn't happen anymore.

Polari is another application that has issues because it uses a frame element under a stack, which under Adwaita has no border, so can be copied with this.

```
stack frame {
    border: none;
}

```

Most of these issues are because the elementary stylesheet has yet to be updated. These tend to show up when using Flatpak versions of the app which are latest, but are relying on the older stylesheet.

**Comment by surajmandalcell** [comment]
check the commit, i added your fix + fixed the eolie uri bar
https://github.com/surajmandalcell/elementary-x/commit/b020b177192e554eb9e8485a8ebe79df3dbe2a30

**Comment by ChocolateMilkGod** [comment]
I think I tried just limiting the not to begin with, but some buttons don't  have .toggle attached to them.

**Comment by surajmandalcell** [comment]
i only tested on eolie and corebird :(
What else do you use? ill install and test more apps for this then.

**Comment by surajmandalcell** [comment]
done, added your fix + hover effect

**Comment by surajmandalcell** [comment]
btw @ChocolateMilkGod what does 
```
stack frame {
    border: none;
}
```
do again?

**Comment by ChocolateMilkGod** [comment]
@surajmandalcell fixes squares in the channel list in Polari that contain the unread count.

**Comment by surajmandalcell** [comment]
crap, the recent changes affected native apps
![image](https://user-images.githubusercontent.com/11650177/40739371-9a0e04a6-6463-11e8-8a63-059e0ef3fdf5.png)
Thinking of a way to only change stuff for gnome apps keeping elementary apps with default styling.
